services:

  db:
    image: bitnami/postgresql:latest
    container_name: postgres-server
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=brevly
    volumes:
      - db:/bitnami/postgresql

volumes:
  db:
